### ISSUE TITLE
Energy consumption

### ISSUE THREAD

**Issue by beneslovas** [rbroker/ecodan-ha-local#41]
Is it possible to use the energy consumption data in the energy board? I can't. Is there any way to get the total electricity consumption so that it can be added to the energy board and it will be calculated by the week of the month or something like that?
![2024-04-09 10_19_42-Energy – Home Assistant](https://github.com/rbroker/ecodan-ha-local/assets/113106805/6fd8e531-62b4-4461-9299-36a6a08c32d1)
Now I get such graphics even with minus

**Comment by rbroker** [comment]
Hi @beneslovas,

The Mitsubishi FTC only tracks (AFAIK) consumption for the last 24h, and the HomeAssistant energy dashboard consumption for individual devices needs "current" information to work properly, unfortunate that means that because the value only updates ~ midnight each night on the FTC, it means it can never work with this part of the homeassistant dashboard.
